### ISSUE TITLE
Compare output

### ISSUE THREAD

**Issue by khatchad** [ponder-lab/Hybridize-Functions-Refactoring#359]
## Summary

Hybridize's `compareOutputTestFile` path (gated by the `edu.cuny.hunter.hybridize.tests.compareOutput` system property) should compare the refactored source against `out/A.py` after the refactoring runs. This issue tracks the **consumer-side integration** in Hybridize. The framework-side test base is tracked at [ponder-lab/Common-Eclipse-Refactoring-Framework#49](https://github.com/ponder-lab/Common-Eclipse-Refactoring-Framework/issues/49).

## Layer 1: `Change.initializeValidationData(...)` (done in #571)

`performChange(change)` calls `Change.isValid()` internally; Eclipse's refactoring API contract requires `Change.initializeValidationData(monitor)` to have run first. Without it, every `compareOutputTestFile` invocation threw:

```
CoreException: TextFileChange has not been initialialized
   at TextFileChange.isValid(TextFileChange.java:193)
```

Fixed by calling `change.initializeValidationData(new NullProgressMonitor())` between `createChange(...)` and `performChange(...)` (#571).

## Layer 2: switch `ResourceStub` to a workspace-backed `IFile` (consumer integration)

After Layer 1, the next failure surfaces:

```
CoreException: Cannot determine URI for '/.../testInferInputSignatureEmission/in/A.py'
   at ResourceFileBuffer.create(ResourceFileBuffer.java:240)
   at TextFileBufferManager.connect(TextFileBufferManager.java:118)
   at TextFileChange.acquireDocument(TextFileChange.java:226)
```

The fixture's `IFile` is an anonymous-class `ResourceStub` override (around line 680 of `HybridizeFunctionRefactoringTest.getFunctions`). Stubs aren't real workspace resources, so `TextFileBufferManager.connect` can't resolve them to URIs.

The framework-side work to provide a `PyDevRefactoringTest` base (with real PyDev-nature `IProject` + workspace-backed `IFile`s) is tracked at [Common-Eclipse-Refactoring-Framework#49](https://github.com/ponder-lab/Common-Eclipse-Refactoring-Framework/issues/49). Once that ships, this issue covers the Hybridize-side consumer integration:

1. Have `HybridizeFunctionRefactoringTest` extend `PyDevRefactoringTest` (instead of the current chain).
2. Replace the `ResourceStub` materialization at ~line 680 with the workspace-backed `IFile`s the new base provides.
3. Existing tests with `out/A.py` files (e.g., `testModel`, `testWildcardImport8/9/10`, `testInferInputSignatureEmission`) should successfully run the compare-output path under `-Dedu.cuny.hunter.hybridize.tests.compareOutput=true`.
4. `testInferInputSignatureEmission` (#565) can drop its manual `TextEdit.apply` and use the `compareOutputTestFile = true` + protected `inferInputSignatures` field shape instead.

## Acceptance

- [x] `Change.initializeValidationData(...)` is called before `performChange(...)` in the compare-output path (#571).
- [ ] [Common-Eclipse-Refactoring-Framework#49](https://github.com/ponder-lab/Common-Eclipse-Refactoring-Framework/issues/49) lands `PyDevRefactoringTest` + the PyDev-nature setup rule.
- [ ] `HybridizeFunctionRefactoringTest` extends the new base and drops the `ResourceStub` override.
- [ ] Existing tests with `out/A.py` files successfully run the compare-output path under `-Dedu.cuny.hunter.hybridize.tests.compareOutput=true`.
- [ ] `testInferInputSignatureEmission` (#565) drops its manual `TextEdit.apply` workaround.

## Cross-Refs

- #571—Layer 1 fix.
- #565—uses manual `TextEdit.apply` as a workaround until this issue's Layer 2 lands.
